[[rsync]]
arch = "aarch64"
git-tree-sha1 = "2679446878240ea066df4191665e757ce606ebef"
os = "macos"

    [[rsync.download]]
    sha256 = "cf1d7017e7e8414e03bc7aaeff53f408c4bdb98000dc521fd1d2c27f12621aa0"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.aarch64-apple-darwin.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "aa3823d7493add168bb8acfbee79ee6ec8da68b3"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "420cbad82dfcb86fd785bb5d5df480ea54f69260dea5647c2c6eaa7ff1a8970c"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.aarch64-linux-gnu.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "bfe1de7274e1050c7997b2d2dfdf474ad97edb96"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "16a3380f5b1e89468fc2a662cc9ac1475ec8d3a988ce19720992b5ca81b09c39"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.aarch64-linux-musl.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "e1c53a0be68555da5d901a43cd40968fe770784b"
os = "freebsd"

    [[rsync.download]]
    sha256 = "7d8a15562ed5ee345ca9843b12b4f41fa20fca8f0bab743687ca794d2fb680f9"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.aarch64-unknown-freebsd.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f416c7d55e5c7601cdf4830671554976a178552"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "349d07ad3cd737f14c6c1da2d9d2f87f14e4698695104ff3907a21216af03967"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.armv6l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ba21ebb20baed4b1c212d3d69b9eb0b5b10181ec"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "bd14cc668ca737bbb5764627e294275dc4dd8c1cdbf22b5df2e572f6aaa5c06a"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.armv6l-linux-musleabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e793324d80e1ae34961507af31c8113b7e63fd29"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "d58415d4bd68ffdb3a4a218018eb8de93b23acd14b1a4a5a3f084beb86700dce"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.armv7l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac0db4e031f912ddc0d7591b117e0c34caaa49b8"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "9e61dd8b66e79db0cd4e608262623996154918653b52e9b43cbd191699e7be8f"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.armv7l-linux-musleabihf.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "398b35e1b60f34c79702b35b52f8a2c3203a06f3"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "d8d2a9f3b278232c1ea555022d5d402a258f603c91f093b42157d22cb91533d3"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.i686-linux-gnu.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "a514c497c0d35492d94445fa2ad5d7a80971b3b3"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "ab575e05e345c6129b31330305ef7db9309fab25b5ea4ebb3951990b972f29aa"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.i686-linux-musl.tar.gz"
[[rsync]]
arch = "powerpc64le"
git-tree-sha1 = "b2590a1dd2b5bfddbf684c4b9eba2bb32398b649"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "45203ee8086ebf27308473495e049ef2350ecdc7c39e24de52f99536169c3743"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.powerpc64le-linux-gnu.tar.gz"
[[rsync]]
arch = "riscv64"
git-tree-sha1 = "6393bd3ac64e929d7321284d5da58acd15ff383c"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "e7b844afee74b039cea379d315657ee8735eebc9bb44176f91f6c0ed08b6e105"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.riscv64-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "9f86c2050cd0b4aa57347284fe63cbe14db5549f"
os = "macos"

    [[rsync.download]]
    sha256 = "71d568b38b6ef467c2feeac89cd98472113d674a93b31bd80efeabad1826510e"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.x86_64-apple-darwin.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "ec8c0674889c88bf47fb87bfd8cec693e8c0f979"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "4fd53d56f9f43acc71eddabd21fb930f694200be41cdee3119727696a4db1ed6"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.x86_64-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "1003a64a552244c2eb26e19dfbb99d081a2ecf28"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "af0c78ecb9bd466756b470cf13280ec368cb7eb9a32613002b8581030c5a97f5"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.x86_64-linux-musl.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "6cac97d57c0c7318e9f73d2b33eac8121955a058"
os = "freebsd"

    [[rsync.download]]
    sha256 = "3c3f91c939439ea846fa5dc68aff871fed6dcde9fbd96a69aeda4d97475cda66"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.0+0/rsync.v3.5.0.x86_64-unknown-freebsd.tar.gz"
