[[rsync]]
arch = "aarch64"
git-tree-sha1 = "b00defa6014308844dcf79ec33326339c8b71c49"
os = "macos"

    [[rsync.download]]
    sha256 = "070ac7404160b6fb36bbc8577c09abc6aaf6a38b9764ac5f9b4e295aca0ab508"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.6+1/rsync.v3.2.6.aarch64-apple-darwin.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "8e756eb80a7014c62d96fbbd4cae658c780b4d11"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "0f47aaf49c38c28c65f72a0494940903bc94d522b1a2a63c11588e2dc49889ed"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.6+1/rsync.v3.2.6.aarch64-linux-gnu.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c8ea44d336078edfaed416285376bf5269aca2c1"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "2ca858b161e6e03ee926b07d3bf3ea00d2b018980460cc7c2a5aaf25d6bd7ca9"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.6+1/rsync.v3.2.6.armv6l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4bfc5ddb9c8b35ed2c1f331d4a6cc6f9ad7f2e8b"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "77d553a1f6ba463ab74d3f6037f3b182f800d7777ade6354ea5278e4135388d8"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.6+1/rsync.v3.2.6.armv7l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "7bdbe63c97735cfc36a288da4d0d6d67ef712415"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "dbe73fc62eb1dc82ff290156cc57aa5970a8db51775c2f91e1e35dc42fd75f28"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.6+1/rsync.v3.2.6.i686-linux-gnu.tar.gz"
[[rsync]]
arch = "powerpc64le"
git-tree-sha1 = "ed629f9258325815bc010f5f0d1edcf8fc9029f4"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "f4e2391c90c12d1d8f34375a120175e74a645e9601b72635c806ddeb15cfcb42"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.6+1/rsync.v3.2.6.powerpc64le-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "556a96517dfaf418914eb605ddd2e4ec94055775"
os = "macos"

    [[rsync.download]]
    sha256 = "41372d8247c13c8c9f11a3e612f2e6c387b3f967ccae300d7f519dac9b8a62e2"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.6+1/rsync.v3.2.6.x86_64-apple-darwin.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "a7c5a3ac9104912299898cadffc636486df10f97"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "99a46ec97995dbae154172637077a4a5e9198e3c78e971e570fbb8d3f8dbf19e"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.6+1/rsync.v3.2.6.x86_64-linux-gnu.tar.gz"
