[[rsync]]
arch = "aarch64"
git-tree-sha1 = "e723635342f352728075f14ae05c9268f3a67227"
os = "macos"

    [[rsync.download]]
    sha256 = "ba51fcf252eb2d7327f71d5ba286a54c533c43830a19ac345aa76d2b07dcdccc"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.aarch64-apple-darwin.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "a1fd37f239839cec49426abdb3ad8fe259f1e396"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "e28fa5821d2b6d6b0efe2d4a4b78be07d15f362415b800f0bcaed8aa222943f5"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.aarch64-linux-gnu.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "1af4580ecaa2d47b1dc4dfce77dddbb1a74b1d60"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "18acfcc750ba45dc9ef1db5b5f562c45f1621433c2bbfc643e6386587dcd7f25"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.aarch64-linux-musl.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "8e16e1279eb5d0fed80085b832848dc13fe91a34"
os = "freebsd"

    [[rsync.download]]
    sha256 = "9b0dfd4e8b52e99671b3d9b534ff55d598d17e67e8dd5a0746ffbbc41ab921cb"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.aarch64-unknown-freebsd.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9648f8676b31f012fabb13ead56686132ab4cbf0"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "cb30365968e595d38365648aab8bcc9a4e545d66a1ec396cf7ce9b44b813fe2f"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.armv6l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ecccc22e6d9f1e97fae2ed6373541b476e168bd"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "9d0c845b041c2947c8ae51d24b395fa8b64ac26082985b9da2713aa162f761d7"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.armv6l-linux-musleabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a77b5e5cc76f7195ec7bfaa2edc4dc330109291e"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "a5e67f68d1dff1eb997966b313f092530b7ee29d86f61413f836be1daee6e939"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.armv7l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "080a74c12894417819dbbe01878662b4c0bd07ff"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "af18b8bf55c7137d08f1b18aee12ce7d4a2e46997700db2cd5733f9b1580ff5d"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.armv7l-linux-musleabihf.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "67c6711fa19d2b48d1d74e6ea976e6faf4de4dbf"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "34a32c09bf5d3fd4c3f0aada9c493d8bc1034947d33d507c29e44ae8a3076f99"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.i686-linux-gnu.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "20eb1e1972bf17a1d5c6497d6d0e116d51a4fa51"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "7d10e1c67a7c11de6206dc0a5aba179f667e12f036580424e7a542f6ec33ac08"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.i686-linux-musl.tar.gz"
[[rsync]]
arch = "powerpc64le"
git-tree-sha1 = "e9a56e6444c99ba1d42c53fd0a9a5babbe45193d"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "dd8cee5d49a3fb202fefa95e222bff3fb4dfe9ca89daa3a6842062448a4cb3de"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.powerpc64le-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "cc99923fc97926d31ff3740db180858e5f3a0155"
os = "macos"

    [[rsync.download]]
    sha256 = "1cf6a12af1496429860398cf0b39907bda30e2eb54493044c20aa8bef76d350c"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.x86_64-apple-darwin.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "31db40c2c5d8ac734f4e971615f9cb7ec1e081ac"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "6434d69361ff633c8304b0b4525df447ae7c958fbf445f4550568a9418ee10b0"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.x86_64-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "bc47efc9302a528fe3fc97423b06c6f003310732"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "b05d809e1190cb2056419f2bd92ddecee7e7296fa8ef8f21816a9ff3d42d80b5"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.x86_64-linux-musl.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "a02f86b17a5726fd4fcb4d900e33f425e678ab97"
os = "freebsd"

    [[rsync.download]]
    sha256 = "3b61c4fcf2b942bb04749ec6451d4fdb7b2319db55a559ded56487616e8b24c2"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.0+0/rsync.v3.4.0.x86_64-unknown-freebsd.tar.gz"
