[[rsync]]
arch = "aarch64"
git-tree-sha1 = "bf7d6119f8350c5d6969ba8a67ff7434daafb743"
os = "macos"

    [[rsync.download]]
    sha256 = "408fbbf0a249712e0e92009dc7601c90f2bb3196236a711ac75ea6815bd2b9d3"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.aarch64-apple-darwin.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "48ae79ebe4dc71b8d0e522cd888fca5c1e3c917c"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "372e5525bbae65e13bd79cd60129a2a0e22de932a1383c506193593ca1952b60"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.aarch64-linux-gnu.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "61e8bad534c2c8b827f2034bceca35f88d34923b"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "756fc12a3c6a3944b5a9e66caf97e5462d2af0e6d76be78bac9dd495a4633018"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.aarch64-linux-musl.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "00d23bd62fbba8ac888f7d0c86f730e83cd8a4e3"
os = "freebsd"

    [[rsync.download]]
    sha256 = "96ea5768c5d9db5bd4b94f719f4f4d16562dd0b3e480bb5ea2b1d75a3ed79ebd"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.aarch64-unknown-freebsd.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3cdb4f84c80e471975b1d0909b2da0c3ec9dd24f"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "f79d9c9cbe79f7a89658ff94ebc387a11c271926d058a56d2b625ce105ddca67"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.armv6l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9bf4ee9cd3e070a2a96c44111e91e786469f150e"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "e4305b0e989b4ddea0bee89f801185e023b020fd26ab066f45bcfd48286df485"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.armv6l-linux-musleabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aaec380f017ddf4bebc61c2b891791319ff763e1"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "04d57dcc245df362fed723c5fcc71cb2d4d2868eeda10fa6765fff5ce0503aa1"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.armv7l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "96c992710d5bff3003b9b44f1b0dbaf5cee08858"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "6cb051ece4a0ba84a59a0f091533bb611af5dd4f521d7084c2c8699d7d31ba09"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.armv7l-linux-musleabihf.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "fc859df2af83a186bc4ab3eb500c4fbbe9931d43"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "7642e557a67fa2577c50e8b62723e919c459462810007d4a711127dda7821354"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.i686-linux-gnu.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "8fbe21299fbeb68f06932272d9b7845d541b4b72"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "ab64e643b4af95105f23b8d121d7990d648353113e91de7e6a6f962abeb18f1d"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.i686-linux-musl.tar.gz"
[[rsync]]
arch = "powerpc64le"
git-tree-sha1 = "d78f0d03e5d1e9428cb0f37c2bf780f83071fc16"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "da67b23f063a57636f7c7b6d41c4e018e2cd6ccb7f8d76115f037753217571ea"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.powerpc64le-linux-gnu.tar.gz"
[[rsync]]
arch = "riscv64"
git-tree-sha1 = "d2c3a4e7a32d7c0d3944f1f87735f66576f6e915"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "8c287bbfcc8e01f8961103c7cf67251177914285c3a3cff4663447150742cf0e"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.riscv64-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "1055e0e993daf7e03432f89bbdba9c07619f5a9d"
os = "macos"

    [[rsync.download]]
    sha256 = "53bd143655c23e1eb0c520a3ac91669e8b5c1cd5b1041c0df3b5130e86ff82ec"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.x86_64-apple-darwin.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "ca9f869cd125bd7e09ef0bde02b529f20c37138a"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "f84fe171db9947f40e07f5e3ef82f10bc95cff1e61d9591c00ac1d08c028e3f5"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.x86_64-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "d02da707cf194b26b9c31d49777ac41d004a8536"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "cab150415ce32bb153157e04125ac39d19736c18634ac0de631cc5d3184a0022"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.x86_64-linux-musl.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "4ce6c7523cd13047e1b5fc8e4dd4ea8867da2f48"
os = "freebsd"

    [[rsync.download]]
    sha256 = "c84bc8d2888031f8d2dc651257c3fe4c6c595dab1b71036f44a6e4b078cdc046"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.5.1+0/rsync.v3.5.1.x86_64-unknown-freebsd.tar.gz"
