[[rsync]]
arch = "aarch64"
git-tree-sha1 = "e6ae2ff160c9bb9a933e92f354b96467ebb1447f"
os = "macos"

    [[rsync.download]]
    sha256 = "82151cc098a4b2a311e490d99c049ae04d72ebda67f08b41171e2b2af7a7d44a"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.7+0/rsync.v3.2.7.aarch64-apple-darwin.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "a8bd5e5c786aab9ddb0e9db393febb672558bca1"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "cdf262bc77c2e06fa532f713b0ca81531e7acee9dd2296de2d7eee27304a0699"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.7+0/rsync.v3.2.7.aarch64-linux-gnu.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "90d50ac595261bb06ce9b4cdbe525b158d11b51d"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "e433dc18762be957f2c9e5234c95e771cb64d6c83420b36c6f420f78317c92c7"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.7+0/rsync.v3.2.7.armv6l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7269941677dca12b1e7ff55c701bbadbcc87329d"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "c8f7af6c20d3d83f6ca3b24bc39dae76fbac0c4751c5930a39d98aa345249364"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.7+0/rsync.v3.2.7.armv7l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "d219147cf43815eff4dc0b82d1074b09f5701ba4"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "30e973762a7e9e1d9910af5b0881cea2f838dc59ab55b6bcfbbf0d7de82a3789"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.7+0/rsync.v3.2.7.i686-linux-gnu.tar.gz"
[[rsync]]
arch = "powerpc64le"
git-tree-sha1 = "aba854f5caf0b28811bed4e6701326dca7f19192"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "ce43dd4243f22b27fa9ccd14a559e09d9ce462887919395e80994e42cb87569c"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.7+0/rsync.v3.2.7.powerpc64le-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "59ae361c57d20aa7beebc575ca3d0336b03e7ce2"
os = "macos"

    [[rsync.download]]
    sha256 = "9eaa89fccc83c47c0f922778b60e4b6a9a28afa96c69c1a3c9265e6e14cb7542"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.7+0/rsync.v3.2.7.x86_64-apple-darwin.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "ae18ab33d5ad518e366db2a9b8ba1cc2f6eb64ed"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "a93c0b59658be718eaeaa8b00eac02cf040469958eb82f5b32bf9948484a5813"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.2.7+0/rsync.v3.2.7.x86_64-linux-gnu.tar.gz"
