[[rsync]]
arch = "aarch64"
git-tree-sha1 = "3c804d7b93b4b35369d41450d5ca0363a4b996cb"
os = "macos"

    [[rsync.download]]
    sha256 = "c98febb80dbff384a86c4cc9d6212ca27c4575bb521afde8afb118db01341cbe"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.aarch64-apple-darwin.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "0ec2cd8da0e64057f73c88cda6d0bd45ab08ccb6"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "28618846fbc66d99bc38f6675d56d54bfc6899e723caf7732da3818be554faa9"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.aarch64-linux-gnu.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "d8b86c7f0b63a10bb8e7f33901f264160c43d7c9"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "11634f036b24c3c1ed0c12c0ffd1478ccf066f7c2edce695ecebb90304fbcf69"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.aarch64-linux-musl.tar.gz"
[[rsync]]
arch = "aarch64"
git-tree-sha1 = "8521636617bb8675bc0906840941064139ee18e8"
os = "freebsd"

    [[rsync.download]]
    sha256 = "0f66af87043d2bb120384ef832cd835fe3205096f23fd3c001aefde1dc4333f2"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.aarch64-unknown-freebsd.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "580b934b7ba23ae91e921b070980a2fcdb3e3f06"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "7e0a1754e5901a504b0b1c0ca8558f7704070146f7d2d9a392de4ff79f7bc930"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.armv6l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb2cceeb656c833364e2fe605fa5a7cb850f6a5a"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "77a5ef1429948f0305b502c7f25b2efcc22732347e9b0098d43e975ef9a3445a"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.armv6l-linux-musleabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "19b0c0f0fdc615d0eab2de6531b3e5d1e5f3ca14"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "1af2787cf36de5d5f58d7069675648432506f8dfb9c6eb277c0fb974c34fc8c0"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.armv7l-linux-gnueabihf.tar.gz"
[[rsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a1ded68f151c8142379c30c11220d237da951df3"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "6f7ebf783aacd250fed86f9321e486abdb27f2f32dd401e00b278e416c602dc8"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.armv7l-linux-musleabihf.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "cf7fb7f0c9020a1c373b9e1743fd339f2bb0ca40"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "4283ed37b73a552d26179b7ddafcef098fb9d5fb42985b7471b41a77dd9ca86e"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.i686-linux-gnu.tar.gz"
[[rsync]]
arch = "i686"
git-tree-sha1 = "a43b831b7cbd360310407853d4564cc7233ed57d"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "d353d75055918ab78702410d4514d2c08b70b57ef0ccdf982d441df299acb73a"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.i686-linux-musl.tar.gz"
[[rsync]]
arch = "powerpc64le"
git-tree-sha1 = "e916934055c8843feedf11b1d0c5eb7ef96c0f7c"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "f98cb6f3db0885fe564233f5b8062cc5b07699066263dbc9957251648f89b517"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.powerpc64le-linux-gnu.tar.gz"
[[rsync]]
arch = "riscv64"
git-tree-sha1 = "eb9f988b2a2cb079f21c78d6793f4970f1f1b2a7"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "a70765f88c40f8216bf98f1853641c558172d9488e74320d87d42937847700cd"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.riscv64-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "1488e39f5fb0ac348912af212abc9d40a406441a"
os = "macos"

    [[rsync.download]]
    sha256 = "b3807e0fd1dcc8d214bfcd395a36e2c98257720243c11531aa2b3033977246fb"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.x86_64-apple-darwin.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "8f87a56d3454b4c02bc05acabac9bc8eb6649c14"
libc = "glibc"
os = "linux"

    [[rsync.download]]
    sha256 = "0b6047e6c198b3ffe3890660a4f59b5c2d687aa5a075617b6d3ebdc333607fc2"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.x86_64-linux-gnu.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "7381ca3552720c1451d2529ce1497e86aaba9526"
libc = "musl"
os = "linux"

    [[rsync.download]]
    sha256 = "bd7299ddab29e1be90fd19896e63ea5bc8924277fe54e388febf480d3ae86f1a"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.x86_64-linux-musl.tar.gz"
[[rsync]]
arch = "x86_64"
git-tree-sha1 = "252b6a14dcf26293eed7cf8a475c04323298ae1a"
os = "freebsd"

    [[rsync.download]]
    sha256 = "cdb706732d97a88620427f6d2aa6bf9b6e3d1fbca5112c3b96b58b87e9c8e632"
    url = "https://github.com/JuliaBinaryWrappers/rsync_jll.jl/releases/download/rsync-v3.4.1+0/rsync.v3.4.1.x86_64-unknown-freebsd.tar.gz"
