# Autogenerated wrapper script for rsync_jll for aarch64-linux-gnu
export rsync

using Zlib_jll
using Popt_jll
using Lz4_jll
using Zstd_jll
using xxHash_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("rsync")
JLLWrappers.@declare_executable_product(rsync)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Popt_jll, Lz4_jll, Zstd_jll, xxHash_jll, OpenSSL_jll)
    JLLWrappers.@init_executable_product(
        rsync,
        "bin/rsync",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
