# Autogenerated wrapper script for rsync_jll for i686-linux-musl
export rsync

using Lz4_jll
using OpenSSL_jll
using Popt_jll
using Zlib_jll
using Zstd_jll
using xxHash_jll
JLLWrappers.@generate_wrapper_header("rsync")
JLLWrappers.@declare_executable_product(rsync)
function __init__()
    JLLWrappers.@generate_init_header(Lz4_jll, OpenSSL_jll, Popt_jll, Zlib_jll, Zstd_jll, xxHash_jll)
    JLLWrappers.@init_executable_product(
        rsync,
        "bin/rsync",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
